#!/bin/bash

CC=${CC-avr-gcc}
TIMES=${TIMES-1}
BASE=${BASE-$base}

AVRTEST_HOME=$(dirname $(which avrtest))
avrtest="${AVRTEST_HOME}/avrtest -q"

Err ()
{
    echo "error: $1"
    exit 1
}

# $1 is some lines of text.
# $2 is the name of some VAR to be assigned a value.
# Find a line like VAR=... in $1 and perform the respective assignment.
# The name of VAR is passed as $2.
getval ()
{
    local l="$(grep "$1=" <<< "$2")"
    eval $l
}

# Set LIBC and CRT according to $builddir.
# When builddir is empty we don't need these variables as AVR GCC
# knows where libc is installed.
set_libs_crt ()
{
    LIBS=
    CRT=
    if [ -n "$builddir" ] ; then
      local multilibdir=$($CC -mmcu=$1 -print-multi-directory)
      # Use the same replacements like in mlib-gen.py::to_ident() and
      # configure.ac's CHECK_AVR_DEVICE.  This flattens out the multilib path.
      # For example, "avr25/tiny-stack" becomes "avr25_tiny_stack",
      # and "." becomes "avr2".
      local multilibdir=$(echo "$multilibdir"     \
                    | sed -e 's:^\.$:avr2:' \
                    | sed -e 's:/:_:g'      \
                    | sed -e 's:-:_:g')
      local crt=crt$1.o
      [ -d "$builddir/avr/devices" ] \
	  || Err "\$builddir/avr/devices = $builddir/avr/devices: not found"
      local incl="-I../../include -I $builddir/include"
      local flags="-nostdlib -nodevicelib -nostartfiles"
      local m="$builddir/avr/lib/$multilibdir"
      CRT=$(find $builddir/avr/devices -name $crt -print | head -1)
      local libs="$m/libc.a $m/libm.a $(dirname $CRT)/lib$1.a -lgcc"
      LIBS="$incl $flags -Wl,-( $libs -Wl,-)"
    fi
}

# Traverse all lines of file $1.
do_func_txt ()
{
    echo
    echo "== $1 =="

    # Line starts:
    # # -> Ignore (comment)
    # ! -> Eval
    # 1 -> Copy line to $out
    # None of these -> run fun_line <line>
    #                  fun_line is provided by the caller script.
    while read -r -u 11 p; do
	case "$p" in
	    "#"* | "" ) ;;
	    !*) eval $(echo "$p" | cut -c 2-) || exit 2 ;;
	    1* )
		[[ "$p" == *'$'* ]] && eval "p=\"$p\""
		cut -c 2- <<< "$p" >> $out
		;;
	    *)
		set_libs_crt $MCU
		fun_line $p
		;;
	esac
    done 11<$1
}

main ()
{
    if [ "$(type -t fun_line)" != "function" ]; then
	Err "fun_line is undefined"
    fi
    [[ -z $BASE ]] && Err "BASE is undefined"
    [[ -z $out  ]] && Err "out is undefined"
    [[ -z $elf  ]] && Err "elf is undefined"

    lst=$(basename $elf .elf).lst

    b="${builddir+builddir=$builddir }"
    c="" && [ $CC != avr-gcc ] && c="CC=$CC "
    t="" && [ $TIMES != 1 ] && t="TIMES=$TIMES "
    B="" && [ $BASE != $base ] && B="BASE=$BASE "

    cat <<EOF > $out
/* Auto-generated file.  DO NOT EDIT, OR YOUR CHANGES WILL BE LOST!
   This file has been auto-generated by:
   $ ${c}${b}${t}${B}$0 $*
*/

/**
EOF

    for f in $*; do
	fil="$BASE-$f.txt"
	[ -f "$fil" ] || Err "$fil: not found"

	do_func_txt $fil
    done

    cat <<EOF >> $out
*/
EOF

    echo "== $out =="
    cat $out
}
