#! /bin/sh
#
# bootstrap script to build all the *.in files and configure script.

: ${AUTOHEADER="autoheader${AC_VER}"}
: ${AUTOCONF="autoconf${AC_VER}"}
: ${ACLOCAL="aclocal${AM_VER}"}
: ${AUTOMAKE="automake${AM_VER}"}

AUTOMAKE="${AUTOMAKE} --foreign --add-missing --copy"

export AUTOMAKE AUTOCONF ACLOCAL AUTOHEADER

# gen-avr-lib-tree.sh calls the Python interpreter on mlib-gen.py
# at the end.  Apparently, mlib-gen.py's shebang "#!/usr/bin/env python"
# does not work on all systems.  So use Autotools AM_PATH_PYTHON to
# determine how to call Python.
(cd devtools; ./configure) || exit 1

# to see what is executed
set -x

rm -rf avr/lib
rm -rf avr/devices
./devtools/gen-avr-lib-tree.sh || exit 1

rm -rf autom4te.cache

${ACLOCAL}
${AUTOHEADER}
${AUTOCONF}
${AUTOMAKE}
